# Generated by Django 4.2.2 on 2023-06-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='stoc',
            field=models.IntegerField(default=0),
        ),
    ]
