# Generated by Django 4.2.2 on 2023-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0003_remove_produs_stoc_produs_imagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='imagine',
            field=models.ImageField(default='imagine_default.jpg', upload_to='media/produse/'),
        ),
    ]
